### ISSUE TITLE
Missing Links

### ISSUE THREAD

**Issue by cacciatc** [fhwang/admin_assistant#11]
Rails version: 3.0.9

After following the set-up guide most of the functionality seems to work except:
- I have no Show, Edit, or New links in the index view.

Also when I attempt to enable destroy no destroy link is rendered.  My controller code:

``` ruby
class Admin::ContactMessagesController < ApplicationController
  layout 'admin'

  admin_assistant_for ContactMessage do |aa|
    aa.actions << :destroy
  end
end

```

I also have tried running the admin_assistant example rails 3.0 and 3.1 apps, but with the same issues as above.  

_Note_:  I can add Show and Edit links manually using the right_column_links method inside the admin_assistant_for block; although, oddly though when I try the  extra_right_column_links_for_index method in my helper module it does not get executed, the same goes for any method I put in there.  

Any ideas?

**Comment by fhwang** [comment]
Yeah, that's a strange one. I can't duplicate this on my side. The fact that you're seeing the same issue in the example apps makes me think this might be due to some strange conflict in the gems you've got locally installed, but that's sort of a stab in the dark.

Try this: Go to the root of one of the sample apps and type "bundle list" -- and then Gist that for me to take a look at? Might be worth a shot.

Also, have you tried running this on other machines or in other rvm gemsets? Are you seeing the same problem there?

**Comment by cacciatc** [comment]
https://gist.github.com/1186864

I will also try it on another machine.

**Comment by fhwang** [comment]
Yeah, nothing there stands out for me -- mind attaching your entire Gemfile? Maybe that could be of help in tracking this down.

**Comment by fhwang** [comment]
rsanheim is also seeing this [ https://github.com/fhwang/admin_assistant/issues/10#issuecomment-2281862 ], but I am unfortunately stumped as to how to duplicate this.

rsanheim, cacciatc: If you create a brand new Rails project, then create one simple model (BlogPost, say), and then add AA, do you see the issue?

**Comment by a9k** [comment]
I'm not sure that the instance variables `@show @edit @new` are ever set in AdminAssistant::Index::View.
I changed it's initialize and things are better - but it's been a 7am-2am day and I won't swear that's a fix.

```
  def initialize(index, action_view, admin_assistant)
    @index, @action_view, @admin_assistant =
        index, action_view, admin_assistant
    @edit = true
    @new = true
    @show = true
  end
```

**Comment by fhwang** [comment]
Yeah, I'm not sure that should matter. For the most part it gets stuff like that from the AdminAssistant class anyway.

BTW, what version of Ruby are you using?

**Comment by a9k** [comment]
ruby 1.9.2p312 (2011-08-11 revision 32926) [x86_64-darwin10.8.0]
Rails 3.0.5

Global search of your code shows no direct assignment of `@edit`. Only `@edit ||= @admin_assistant.edit?` But that is `def edit?` so just recursively looking at an never set variable. Please point me to a file/line number where `@edit` ia set.

**Comment by fhwang** [comment]
Oh, actually, it's only used for local memoization. The call to `@edit ||= @admin_assistant.edit?` will set `@edit` the first time so it doesn't have to call `@admin_assistant.edit?` the second time.

(That's not technically true; if `@admin_assistant.edit?` returns false, then it will set `@edit` to false but keep calling `@admin_assistant.edit?` from then on, so it's not the world's smartest memoization. But I'd be surprised if that was was causing any sort of bug.)

I'm wondering about Ruby 1.9, though, which I don't use a lot. cacciatc, what Ruby are you using?

**Comment by cacciatc** [comment]
ruby 1.9.2p180 (2011-02-18 revision 30909) [i686-linux]

**Comment by a9k** [comment]
I'm wondering if it has to do with the conversion of nil to false. Possibly a subtle 1.9 "feature"?
Another test--
If I insert in admin_assitant.rb: (adding to AdminAssistant top level class)

```
def edit?
  p "super #{defined?(@edit).inspect} #{@edit.inspect}"
  @edit
end
```

I get back `"super nil nil"` in console and edit links appear. If I remove this extra `edit?` method, something gets called that returns false. Where that `edit?` is I don't know! Maybe it's an undefined method handler? Are you relying on some mixin to define `edit?` ? I just don't see where there is another `edit?` outside of AdminAssistant::Index::View.

**Comment by fhwang** [comment]
The falsiness of nil is a pretty core aspect of Ruby and has been for some time -- I'd be super-surprised if anything around there changed.

In case you're wondering, `AdminAssistant#edit?` is handled in `method_missing`. `admin_assistant.rb` lines 166-167, which dispatch to `supports_action?`

Ruby 1.9 is not happy trying to build on my MBP, but I'll try to get it set up there and see if the test suite passes there.

**Comment by a9k** [comment]
Thanks for pointer. I wondered if there was a missing method thing going on but missed it.
Yes agreed nil interpreted as logical has always been false. In this case it's not nil but false returned supports_action? that is passed back to edit? (::View).

Maybe something in supports_action? behaves differently between 1.8 and 1.9. That seems doubtful.

I usually stick with a tough problem but I had to bail on using your code and patch ActiveScaffold up to get client happy. Maybe I can tackle AdminAssistant again later. I left a dangling code branch to come back to. ActiveScaffold is fairly broken these days. I tried 3 alternates to ActiveScaffold on Friday. AdminAssistant was on list because it mentioned FileColumn support. 

Hope you get the 1.9 running on your MBP.

**Comment by fhwang** [comment]
I could see it being something about method_missing. Hoping to get Ruby 1.9 built locally so I can investigate further. And no worries about ActiveScaffold -- obviously you should do what makes the most sense for your situation.

Hopefully I can find some time to finally fix this issue soon.

**Comment by fhwang** [comment]
Oh, I can't test this out yet, but this looks like it might be the fix:

https://github.com/gregwebs/admin_assistant/commit/405901f392fe003afcf59ea817da21d2e187754d

**Comment by fhwang** [comment]
Yeah, as suspected, it was an issue that greg's commit fixed, though I had to tweak it to get it to work in both 1.9 and 1.8. If you're curious, the problem was that Object#public_instance_methods returns an array of symbols in 1.9 and an array of strings in 1.8.

I haven't stamped a new gem version for this yet, but please feel try it out from my master and let me know if you see any other issues.
