### ISSUE TITLE
AdminAssistant/Rails 3.0.10/MySQL can break rake db:migrate

### ISSUE THREAD

**Issue by jrallison** [fhwang/admin_assistant#15]
We've run into a problem using AdminAssistant on one of our apps using Rails 3.0.10.

If you have AdminAssistant setup for certain models, drop your database, and rebuild the schema using `rake db:migrate`, it will fail with an error about database tables not existing.

I was able to reproduce with a fresh Rails 3.0.10 app.  This gist has the changes needed to cause the error:

https://gist.github.com/1483238

Any ideas on ways to solve this?

**Comment by fhwang** [comment]
Hi John,

Yeah, it looks like the initialization is being overly aggressive in what it assumes about the state of the database. Let me try to get in a fix sometime tonight or tomorrow.

FH

**Comment by fhwang** [comment]
Hey John,

So actually, there was already code in there that deals with this circumstance, but it was failing for you because Rails 3.0 doesn't wrap the exceptions into any generic exception class, and the AA code was only catching ActiveRecord::StatementInvalid and not Mysql::Error. This is now fixed in 2.2.4.

F

**Comment by jrallison** [comment]
Thanks for the help, Francis!
