### ISSUE TITLE
 Version 1.0 declares "mislav-will_paginate" as a dependency.

### ISSUE THREAD

**Issue by nodanaonlyzuul** [fhwang/admin_assistant#19]
I inherited a project that is using version 1.0.0 as a **plugin**.
Obviously I'm removing the project's plugins in favor of gems...

The problem is that the gemspec has a dependency on "mislav-will_paginate" - which isn't the name of the gem anymore.

I'm having a hard time finding a branch / tag at version 1.0.0 - if you point me towards it I can change the dependency to a version of will_paginate that I know works Rails 2.3.4.

I expect you to fix this by EOD.
No excuses - this is mission critical.
Good morning Francis.

**Comment by fhwang** [comment]
You are a demanding taskmaster, Stephen.

1.0.2 is dependent on will_paginate as opposed to mislav-will_paginate. You should be able to upgrade to that and not deal with any breakage. Can you give that a try?

**Comment by nodanaonlyzuul** [comment]
Hey Slim...

I put a requirement for `"admin_assistant",  "1.0.1"` in our `Gemfile`.
But get a `uninitialized constant AdminAssistant::Request::Base` when I bring the app up on my browser.

**Comment by fhwang** [comment]
So, yeah, how about that 1.0.2? Which is a different version than 1.0.1.

**Comment by nodanaonlyzuul** [comment]
Well - I'm tired of being talked down to in such a public forum...

1.0.2 (thank btw) still throws the same exception.
Here's a stracktrace: https://gist.github.com/4163204.

**Comment by nodanaonlyzuul** [comment]
I'll have time to dig into this a bit tomorrow...

**Comment by fhwang** [comment]
You're probably using Ruby 1.9, right? I think this was a 1.9 issue that was solved later, but should be fairly easy to put into the 1.0 version stream. Lemme take a look at this later.

**Comment by nodanaonlyzuul** [comment]
Actually - we're using that most gangster of MRI versions..1.8.7.

**Comment by fhwang** [comment]
So, it has been a long time since I did anything with Ruby 1.8.7, Rails 2, or admin_assistant 1. So it's hard for me to really be sure what the bug is and exactly how to verify that I've fixed it. However,

I think the culprit is the top of lib/admin_assistant.rb, the part that uses Find.find. Before I was relying too much on the implicit sorting order in Find.find, but I think at some point that sorting order changed in Ruby, thus causing this breakage.

Most likely the fix here is the same as the top of this commit:

https://github.com/fhwang/admin_assistant/commit/d1bb5be6c1a29bfc85a1037289302b4af4f791b6

... where it simply lists the files explicitly. I'd recommend doing something similar, only in the v1 branch.

Let me know if that's helpful. We could also try to do this tomorrow night before or after Goruco planning, on your laptop.

**Comment by fhwang** [comment]
Hey Stephen,

I don't know if you're still dealing with this issue, or even if we are still friends. But if so, I just pushed 1.0.3, which should hopefully fix this issue.

**Comment by fhwang** [comment]
Actually hold off, 1.0.3 was an incorrect publish from master. Let me get you a 1.0.4 to try in a bit.

Yarg. I don't know what I'm doin'.

**Comment by fhwang** [comment]
Try 1.0.4 now d00d.

**Comment by fhwang** [comment]
Hey Stephen, this issue from nine months ago is fixed for you, yeah?

**Comment by nodanaonlyzuul** [comment]
It is.
