### ISSUE TITLE
uninitialized constant AdminAssistant::Request::Base

### ISSUE THREAD

**Issue by coreyti** [fhwang/admin_assistant#3]
Following up on the [last issue I posted](https://github.com/fhwang/admin_assistant/issues#issue/2):

When I try to use the github-hosted version (as a gem...)

```
gem "admin_assistant",
    :git => "git://github.com/fhwang/admin_assistant.git"`
```

I get:

```
uninitialized constant AdminAssistant::Request::Base
```

While `AdminAssistant::Request::Base` does exist, It seems the files are not required in the, um, _required_ order.

Thanks again,
Corey

**Comment by fhwang** [comment]
Corey, I'm not able to replicate this bug. What version of Rails are you using?

**Comment by coreyti** [comment]
Hi Francis,

That was with Rails 3.0.1

Thanks,
Corey

**Comment by fhwang** [comment]
Hey Corey, just an update so you think I haven't forgotten about this -- basically AA doesn't support Rails 3 yet. Embarrassing!

I'm working on adding Rails 3 support, but since I'm trying to keep the same gem working across Rails 2 & Rails 3, it might take me a little while. But this is at the front of my open-source queue.

**Comment by coreyti** [comment]
Hey Francis,

Thanks for the note.  If you're interested, I've got what I think is a pretty good setup for testing a gem against multiple Rails versions with my [engine-assets](https://github.com/coreyti/engine-assets/) project.
- Corey
